title: Sharad Shriram
email: sharadsriram@iisc.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: /
url: "https://sharadshriram.github.io"

# Social handles
twitter_username: drozyNerd
github_username:  sharadshriram
linkedin_username: sharadshriram
rss: rss

# Excerpts
show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
